config := "./config.toml"
default: main
jobname := "$( tomlq jobname -f" + config + ")"
outdir := "$( tomlq outdir -f" + config + ")"

files := "main.tex"

alias r := refs
alias b := pdf
alias b2 := pdf2
alias c := clean

main: pdf refs pdf2

refs:
	biber {{outdir}}/{{jobname}}

pdf:
	lualatex --output-format=pdf --output-directory={{outdir}} --jobname={{jobname}} --synctex=1 --interaction=nonstopmode --file-line-error {{files}}

pdf2: && pdf
	lualatex --output-format=pdf --output-directory={{outdir}} --jobname={{jobname}} --synctex=1 --interaction=nonstopmode --file-line-error {{files}}

clean:
	rm {{outdir}}/*.aux {{outdir}}/*.bbl {{outdir}}/*.bcf {{outdir}}/*.blg {{outdir}}/*.log {{outdir}}/*.out {{outdir}}/*.toc